name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '14.x'

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install dependencies
      run: python -m pip install jupyterlab --pre

    - name: Install the extension
      run: |
        python -m pip install .

    - name: Check the server, classic and lab extensions are installed
      run: |
        jupyter serverextension list 2>&1 | grep -ie "jupyter_resource_usage.*enabled"
        jupyter server extension list 2>&1 | grep -ie "jupyter_resource_usage.*enabled"
        jupyter nbextension list 2>&1 | grep -ie "jupyter_resource_usage/main.*enabled"
        jupyter labextension list 2>&1 | grep -ie "@jupyter-server/resource-usage.*OK"
        python -m jupyterlab.browser_check

    - name: Lint
      run: |
        cd packages/labextension/
        jlpm
        jlpm run lint:check
